# Generated by Django 2.0.3 on 2018-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=15)),
                ('moviePoster', models.CharField(max_length=1000)),
            ],
        ),
    ]
