# Generated by Django 2.0.3 on 2018-04-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_seat_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviePoster',
            field=models.CharField(max_length=10000),
        ),
    ]
